"""add bookings.seat_ids

Revision ID: 263d962dba7a
Revises: 6a15cecb828f
Create Date: 2026-09-01 10:10:31.228744

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "263d962dba7a"
down_revision: str | Sequence[str] | None = "6a15cecb828f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("seat_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "seat_ids")
    # ### end Alembic commands ###
