"""idempotency keys, payment events, outbox

Revision ID: 6a15cecb828f
Revises: 77e044b6f4b8
Create Date: 2026-09-01 09:47:52.901160

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a15cecb828f"
down_revision: str | Sequence[str] | None = "77e044b6f4b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("request_fingerprint", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')",
            name=op.f("ck_idempotency_keys_idempotency_key_status_valid"),
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index(
        op.f("ix_idempotency_keys_created_at"),
        "idempotency_keys",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'IN_PROGRESS'"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("aggregate_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    op.create_index(
        op.f("ix_outbox_created_at"),
        "outbox",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "payment_events",
        sa.Column("provider_event_id", sa.String(), nullable=False),
        sa.Column("booking_id", sa.BigInteger(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_status", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_payment_events_booking_id_bookings"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("provider_event_id", name=op.f("pk_payment_events")),
    )
    op.create_index(
        op.f("ix_payment_events_booking_id"), "payment_events", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_events_received_at"),
        "payment_events",
        ["received_at"],
        unique=False,
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.drop_index(op.f("ix_bookings_idempotency_key"), table_name="bookings")
    op.create_index(
        op.f("ix_bookings_idempotency_key"),
        "bookings",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###

    # NOT auto-detected -- confirmed directly (autogenerate produced nothing
    # for this table at all despite the model change). Alembic's
    # autogenerate does not reliably diff CheckConstraint bodies, only
    # presence/absence by name, so widening an existing constraint's
    # allowed values requires a manual drop+recreate. See CLAUDE.md/
    # app/domain/models.py's BookingStatus.REFUND_REQUIRED (Phase 5): a
    # payment.succeeded webhook can arrive after a booking's hold expired
    # and the seat was resold, and that booking must be representable as
    # something other than PENDING/CONFIRMED/CANCELLED/REFUNDED.
    op.drop_constraint(op.f("ck_bookings_booking_status_valid"), "bookings", type_="check")
    op.create_check_constraint(
        "booking_status_valid",
        "bookings",
        "status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED', 'REFUND_REQUIRED')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_bookings_booking_status_valid"), "bookings", type_="check")
    op.create_check_constraint(
        "booking_status_valid",
        "bookings",
        "status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bookings_idempotency_key"),
        table_name="bookings",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_bookings_idempotency_key"), "bookings", ["idempotency_key"], unique=False
    )
    op.drop_index(
        op.f("ix_payment_events_received_at"),
        table_name="payment_events",
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.drop_index(op.f("ix_payment_events_booking_id"), table_name="payment_events")
    op.drop_table("payment_events")
    op.drop_index(
        op.f("ix_outbox_created_at"),
        table_name="outbox",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox")
    op.drop_index(
        op.f("ix_idempotency_keys_created_at"),
        table_name="idempotency_keys",
        postgresql_where=sa.text("status = 'IN_PROGRESS'"),
    )
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
