"""add hold_audit table

Revision ID: 77e044b6f4b8
Revises: b69852358522
Create Date: 2026-08-28 20:46:05.770914

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77e044b6f4b8"
down_revision: str | Sequence[str] | None = "b69852358522"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hold_audit",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("seat_id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["seat_id"], ["seats.id"], name=op.f("fk_hold_audit_seat_id_seats"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hold_audit")),
    )
    op.create_index(op.f("ix_hold_audit_seat_id"), "hold_audit", ["seat_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hold_audit_seat_id"), table_name="hold_audit")
    op.drop_table("hold_audit")
    # ### end Alembic commands ###
