"""initial schema

Revision ID: b69852358522
Revises:
Create Date: 2026-08-28 19:58:10.555902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b69852358522"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("venue", sa.String(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_seats", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED')",
            name=op.f("ck_bookings_booking_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_bookings_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
    )
    op.create_index(
        op.f("ix_bookings_idempotency_key"), "bookings", ["idempotency_key"], unique=False
    )
    op.create_table(
        "seats",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("row_label", sa.String(), nullable=False),
        sa.Column("seat_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("held_by_session_id", sa.String(), nullable=True),
        sa.Column("hold_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("booking_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('AVAILABLE', 'HELD', 'BOOKED')", name=op.f("ck_seats_seat_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_seats_booking_id_bookings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_seats_event_id_events"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seats")),
        sa.UniqueConstraint(
            "event_id",
            "section",
            "row_label",
            "seat_number",
            name=op.f("uq_seats_event_id_section_row_label_seat_number"),
        ),
    )
    op.create_index(op.f("ix_seats_event_id_status"), "seats", ["event_id", "status"], unique=False)
    op.create_index(
        op.f("ix_seats_hold_expires_at"),
        "seats",
        ["hold_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'HELD'"),
    )
    op.create_table(
        "booking_seats",
        sa.Column("booking_id", sa.BigInteger(), nullable=False),
        sa.Column("seat_id", sa.BigInteger(), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_seats_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["seat_id"],
            ["seats.id"],
            name=op.f("fk_booking_seats_seat_id_seats"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("booking_id", "seat_id", name=op.f("pk_booking_seats")),
    )
    op.create_index(
        op.f("ix_booking_seats_seat_id"),
        "booking_seats",
        ["seat_id"],
        unique=True,
        postgresql_where=sa.text("released_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_booking_seats_seat_id"),
        table_name="booking_seats",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_table("booking_seats")
    op.drop_index(
        op.f("ix_seats_hold_expires_at"),
        table_name="seats",
        postgresql_where=sa.text("status = 'HELD'"),
    )
    op.drop_index(op.f("ix_seats_event_id_status"), table_name="seats")
    op.drop_table("seats")
    op.drop_index(op.f("ix_bookings_idempotency_key"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_table("events")
    # ### end Alembic commands ###
