"""composite primary key on idempotency_keys for user scoping

Revision ID: cd8815978689
Revises: 263d962dba7a
Create Date: 2026-09-01 10:58:15.570685

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd8815978689"
down_revision: str | Sequence[str] | None = "263d962dba7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bookings_idempotency_key"),
        table_name="bookings",
        postgresql_where="(idempotency_key IS NOT NULL)",
    )
    op.create_index(
        op.f("ix_bookings_user_id_idempotency_key"),
        "bookings",
        ["user_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###

    # NOT auto-detected -- confirmed directly, same as this phase's
    # earlier bookings.status CHECK constraint amendment: Alembic's
    # autogenerate does not detect primary key changes either. Security
    # fix (see IdempotencyKeyRow's own docstring): key alone as the
    # primary key let a second user's request collide with a DIFFERENT
    # user's row on a client-supplied, untrusted Idempotency-Key value.
    op.drop_constraint(op.f("pk_idempotency_keys"), "idempotency_keys", type_="primary")
    op.create_primary_key(op.f("pk_idempotency_keys"), "idempotency_keys", ["user_id", "key"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("pk_idempotency_keys"), "idempotency_keys", type_="primary")
    op.create_primary_key(op.f("pk_idempotency_keys"), "idempotency_keys", ["key"])

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bookings_user_id_idempotency_key"),
        table_name="bookings",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_bookings_idempotency_key"),
        "bookings",
        ["idempotency_key"],
        unique=True,
        postgresql_where="(idempotency_key IS NOT NULL)",
    )
    # ### end Alembic commands ###
